"""Factory for non-``html.Div`` wrapper classes.

``make_wrapper_class(container_cls)`` returns a cached
``Generic[T]``-parameterised subclass of the given Dash container that
inherits adapter behaviour from ``_WrapperMixin``. This is the tier-2
subclassing target used for semantic HTML containers such as
``html.Figure``, ``html.Section``, ``html.Article``, ``html.Aside``.

The ``html.Div`` entry is pre-populated with the public
``ComponentWrapper`` so callers get the same class whether they use the
factory or import ``ComponentWrapper`` directly.
"""

from __future__ import annotations

from typing import Any, Generic, TypeVar

from dash import html
from dash.development.base_component import Component

from ._wrapper import ComponentWrapper, _WrapperMixin

T = TypeVar("T", bound=Component)


_CLASS_CACHE: dict[type[Component], type[Any]] = {html.Div: ComponentWrapper}


def make_wrapper_class(container_cls: type[Component]) -> type[Any]:
    """Return a cached wrapper class for ``container_cls``.

    The returned class subclasses ``_WrapperMixin`` and
    ``container_cls`` and is ``Generic[T]``-parameterisable, so users
    can write
    ``class Foo(make_wrapper_class(html.Figure)[dcc.Graph]): ...``.

    Parameters
    ----------
    container_cls : type[Component]
        A subclass of ``dash.development.base_component.Component`` —
        in practice, an ``html.*`` container class such as
        ``html.Figure`` or ``html.Section``.

    Returns
    -------
    type
        A subclass of ``container_cls`` and ``_WrapperMixin``, cached
        per ``container_cls`` so repeated calls return the same
        class. For ``container_cls=html.Div`` this returns the public
        :class:`ComponentWrapper`.

    Raises
    ------
    TypeError
        If ``container_cls`` is not a subclass of ``Component``.

    See Also
    --------
    wrap : High-level factory that calls this internally and returns
        a wrapper *instance* rather than a class.
    ComponentWrapper : The pre-built ``html.Div`` wrapper class.

    Examples
    --------
    >>> from dash import dcc, html
    >>> from dash_wrap import make_wrapper_class
    >>> FigureWrapper = make_wrapper_class(html.Figure)
    >>> class CaptionedChart(FigureWrapper[dcc.Graph]):
    ...     def __init__(self, graph, caption):
    ...         super().__init__(
    ...             graph,
    ...             proxy_props=["figure", "config"],
    ...             children=[graph, html.Figcaption(caption)],
    ...         )
    """
    if not (isinstance(container_cls, type) and issubclass(container_cls, Component)):
        raise TypeError(
            "container_cls must be a subclass of "
            "dash.development.base_component.Component, got "
            f"{container_cls!r}."
        )

    cached = _CLASS_CACHE.get(container_cls)
    if cached is not None:
        return cached

    # ty cannot resolve the MRO of a class whose base is a type-variable
    # alias; suppress just that diagnostic here. Runtime behaviour is
    # unchanged — Python happily walks the MRO at instantiation time.
    class _Wrapper(_WrapperMixin, container_cls, Generic[T]):  # ty: ignore[unsupported-base]
        __doc__ = (
            f"{container_cls.__name__}-based component wrapper generated by "
            "dash_wrap.make_wrapper_class."
        )

    _Wrapper.__name__ = f"{container_cls.__name__}Wrapper"
    _Wrapper.__qualname__ = _Wrapper.__name__
    _Wrapper.__module__ = __name__
    _CLASS_CACHE[container_cls] = _Wrapper
    return _Wrapper
